// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewShore.ETCore.Repositories.DataContext;

#nullable disable

namespace NewShore.ETCore.Repositories.Migrations
{
    [DbContext(typeof(NewShoreContext))]
    [Migration("20230122183921_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewShoreEntities.DTOs.CreateFlightDTO", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<double?>("Price")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("float")
                        .IsFixedLength();

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasColumnType("nchar")
                        .IsFixedLength();

                    b.HasKey("FlightId");

                    b.ToTable("Flights");
                });

            modelBuilder.Entity("NewShoreEntities.DTOs.CreateJourneyFlightDTO", b =>
                {
                    b.Property<int>("JourneyFlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JourneyFlightId"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Flights")
                        .IsRequired()
                        .HasColumnType("nchar")
                        .IsFixedLength();

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<double>("Price")
                        .HasMaxLength(3)
                        .HasColumnType("float")
                        .IsFixedLength();

                    b.HasKey("JourneyFlightId");

                    b.ToTable("Journeys");
                });

            modelBuilder.Entity("NewShoreEntities.DTOs.CreateJourneyRouteDTO", b =>
                {
                    b.Property<int>("JourneyFlightId")
                        .HasColumnType("int");

                    b.Property<int>("JourneyId")
                        .HasColumnType("int");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.HasKey("JourneyFlightId", "JourneyId", "FlightId");

                    b.ToTable("FJourneys");
                });

            modelBuilder.Entity("NewShoreEntities.DTOs.CreateTransportDTO", b =>
                {
                    b.Property<int>("TransportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransportId"));

                    b.Property<string>("FlightCarrier")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nchar(5)")
                        .IsFixedLength();

                    b.HasKey("TransportId");

                    b.ToTable("Transports");
                });
#pragma warning restore 612, 618
        }
    }
}
